[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.lint]
# Enforce: pycodestyle (E/W), pyflakes (F), import sort (I), naming (N), docstrings (D)
select = ["E", "W", "F", "I", "N", "D"]

# Relax a few docstring rules most teams ignore early on:
ignore = ["D100", "D104", "D107", "D401"]

# Pick one from each incompatible pair:
# - D203 vs D211  → keep D211 (no-blank-line-before-class), ignore D203
# - D212 vs D213  → keep D213 (multi-line summary on 2nd line), ignore D212
extend-ignore = ["D203", "D212"]

[tool.ruff.lint.isort]
combine-as-imports = true
